"""modified tables

Revision ID: bbde006bb25b
Revises: 1152d15c3f25
Create Date: 2023-07-06 17:25:56.449001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbde006bb25b'
down_revision = '1152d15c3f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('id')
        batch_op.drop_column('updates_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updates_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
